# Generated by Django 5.0.2 on 2024-02-27 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('nested', models.BooleanField(default=False)),
                ('nested_id', models.CharField(max_length=100)),
                ('house_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.houses')),
            ],
        ),
    ]
